# Grouped Relative Policy Optimization (GRPO) tuned for 2 nodes, Qwen3-1.7B.
# Run with:
#   python -m apps.grpo.main --config apps/grpo/qwen3_1_7b_2node.yaml
#

group_size: 4        # was 8
local_batch_size: 8  # was 16
max_req_tokens: 512  # was 1024
max_res_tokens: 1024 # was 2048
model: "Qwen/Qwen3-1.7B"
off_by_n: 1

provisioner:
  launcher: slurm

rollout_threads: 1

metric_logging:
  wandb:
    project: grpo-training
    group: grpo_exp_${oc.env:USER}
    logging_mode: global_reduce
  console:
    logging_mode: global_reduce

dataset:
  path: "openai/gsm8k"
  revision: "main"
  data_split: "train"
  streaming: true
  model: ${model}

policy:
  engine_args:
    model: ${model}
    tensor_parallel_size: 8
    pipeline_parallel_size: 1
    enforce_eager: false
  sampling_params:
    n: ${group_size}
    max_tokens: ${max_res_tokens}
    temperature: 1.0
    top_p: 1.0

trainer:
  model:
    name: qwen3
    flavor: 1.7B
    hf_assets_path: hf://${model}
  optimizer:
    name: AdamW
    lr: 1e-5
    eps: 1e-8
  lr_scheduler:
    warmup_steps: 1
  training:
    local_batch_size: ${local_batch_size}
    seq_len: ${sum:${max_req_tokens},${max_res_tokens}}
    max_norm: 1.0
    steps: 1000000
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 1
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
    disable_loss_parallel: true
  checkpoint:
    enable: true
    folder: ./checkpoint
    initial_load_path: hf://${model}
    initial_load_in_hf: true
    last_save_in_hf: true
    interval: 500
    async_mode: "disabled"
  activation_checkpoint:
    mode: full

replay_buffer:
  batch_size: ${local_batch_size}
  max_policy_age: ${off_by_n}
  dp_size: 1

ref_model:
  model:
    name: qwen3
    flavor: 1.7B
    hf_assets_path: hf://${model}
  training:
    seq_len: ${trainer.training.seq_len}
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 1
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
  checkpoint:
    enable: true
    initial_load_path: hf://${model}
    initial_load_in_hf: true

services:
  policy:
    procs: ${policy.engine_args.tensor_parallel_size}
    num_replicas: 1
    hosts: 1
    with_gpus: true
    mesh_name: policy
  ref_model:
    procs: ${ref_model.parallelism.tensor_parallel_degree}
    num_replicas: 1
    with_gpus: true
    mesh_name: ref_model
  reward_actor:
    procs: 1
    num_replicas: 1
    with_gpus: false
    mesh_name: reward_actor

actors:
  dataset:
    procs: 1
    with_gpus: false
    mesh_name: dataset
  trainer:
    procs: ${trainer.parallelism.tensor_parallel_degree}
    hosts: 1
    with_gpus: true
    mesh_name: trainer
  replay_buffer:
    procs: 1
    with_gpus: false
    mesh_name: replay_buffer
  compute_advantages:
    procs: 1
    with_gpus: false
    mesh_name: compute_advantages
